### ISSUE TITLE
I could not login or register in the system

### ISSUE THREAD

**Issue by chenchonghz** [sscotti/MWL_PDF_OrthancDemo#1]
Have some issue with the cookie?

**Comment by sscotti** [comment]
This is kind of an outdated package.  I might replace it with an updated one shortly.  If you are not familiar with Laravel though, that might be your problem.  Make sure you did the following and the other steps and made adjustments for your system.

Copy / Rename .env.example to .env in the laravel folder
Copy / Rename PACS_Integration/php-fpm-nginx/default.conf.example.conf to default.conf. That is the config for nginx.

If you need help you can contact me directly.

**Comment by chenchonghz** [comment]
I am very glad to receive your reply.Yes I am not familiar with Laravel  and got it now. 
You do greate work.

**Comment by sscotti** [comment]
Good.  Although I recently replaced the prior repo with a newer version that does not have the Laravel front-end.  The new one is mostly for Orthanc Python script development and Modality Worklist development.
